
[outputs.log]
destination = "stdout" # options are stdout or a file path. defaults to stdout
format = "logstash" # options are pretty or logstash. defaults to pretty

[outputs.influxdb]
db="metrics"
defaultTags={app="myapp-chaperone"}
uri="http://localhost:8086"

