version: "2.4"

services:
  influxdb:
    image: influxdb:1.5
    container_name: chaperone_influxdb
    networks:
      - app
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"

  grafana:
    image: grafana/grafana:latest
    container_name: chaperone_grafana
    networks:
      - app
    ports:
      - "3000:3000"
    environment:
      # the statusmap panel works great with checks, and is used in the sample dashboard that can be imported.
      - GF_INSTALL_PLUGINS=flant-statusmap-panel

  chaperone:
    build: .
    networks:
      - app
    depends_on:
      - influxdb
    environment:
      # you can override most chaperone configuration values through environment variables. just use the "CHAPERONE_" prefix.
      - CHAPERONE_OUTPUTS_INFLUXDB_URI=http://influxdb:8086

networks:
  app:
