name: docker-multiplatform

on:
  workflow_dispatch:

env:
  IMAGE_NAME: edgescope/chaperone

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: gradle create app tar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distTar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          #push: false
          tags: |
            ${{ env.IMAGE_NAME }}:${GITHUB_REF_NAME}
            ${{ env.IMAGE_NAME }}:test
#            ${{ env.IMAGE_NAME }}:latest
