name: docker-hub-publish

on:
  release:
    types: [created]

env:
  IMAGE_NAME: edgescope/chaperone

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: gradle create app tar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distTar

      - name: Build image
        run: >
          docker build
          --tag "edgescope/chaperone:${GITHUB_REF_NAME}"
          --tag "edgescope/chaperone:latest"
          .

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u dbtanner --password-stdin

      - name: Push image
        run: |
          docker push --all-tags edgescope/chaperone
